import { useState, useEffect } from 'react';
import { useTaskStore } from '../store/taskStore';
import { useUiStore } from '../store/uiStore';
import { recommendationsApi, type Recommendation } from '../api/recommendations.api';
import { tasksApi } from '../api/tasks.api';

const TONE_BG: Record<string, string> = {
  crimson: 'rgba(139,0,0,0.20)', amber: 'rgba(245,158,11,0.14)', green: 'rgba(52,211,153,0.12)', violet: 'rgba(139,92,246,0.16)',
};
const TONE_BORDER: Record<string, string> = {
  crimson: 'rgba(239,68,68,0.30)', amber: 'rgba(245,158,11,0.30)', green: 'rgba(52,211,153,0.30)', violet: 'rgba(139,92,246,0.30)',
};

export function RecommendationsView() {
  const { updateTask, setFilters } = useTaskStore();
  const { navigate, addToast } = useUiStore();
  const [recs, setRecs] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(false);
  const [geminiOn, setGeminiOn] = useState(false);

  useEffect(() => {
    recommendationsApi.status().then(res => setGeminiOn(res.data.enabled)).catch(() => {});
  }, []);

  async function handleGenerate() {
    setLoading(true);
    try {
      const res = await recommendationsApi.generate();
      setRecs(res.data.recommendations);
      setGeminiOn(res.data.source === 'gemini');
      if (res.data.error) addToast({ message: `Recommendations failed: ${res.data.error}`, type: 'error' });
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message || 'Failed to generate';
      addToast({ message: `Recommendations failed: ${msg}`, type: 'error' });
    } finally {
      setLoading(false);
    }
  }

  async function handleAction(rec: Recommendation) {
    switch (rec.actionType) {
      case 'start':
        if (rec.taskId) {
          const res = await tasksApi.update(rec.taskId, { status: 'In Progress' }).catch(() => null);
          if (res) { updateTask(rec.taskId, res.data.task); navigate('tasks'); }
        }
        break;
      case 'reschedule':
        if (rec.taskId) {
          const tomorrow = new Date(); tomorrow.setDate(tomorrow.getDate() + 1);
          const res = await tasksApi.update(rec.taskId, { deadline: tomorrow.toISOString().slice(0, 10) }).catch(() => null);
          if (res) updateTask(rec.taskId, res.data.task);
        }
        break;
      case 'rebalance': {
        const res = await tasksApi.autoSchedule().catch(() => null);
        if (res) useTaskStore.getState().setTasks(res.data.tasks);
        break;
      }
      case 'filterWork':
        navigate('tasks'); setFilters({ category: 'Work' });
        break;
      case 'showBacklog':
        navigate('tasks'); setFilters({ status: 'Pending' });
        break;
    }
    addToast({ message: 'Action applied', type: 'success' });
  }

  return (
    <section>
      {/* Header card */}
      <div className="card p-6 flex items-center gap-4 flex-wrap">
        <div className="w-12 h-12 rounded-xl grid place-items-center text-2xl shrink-0" style={{ background: 'linear-gradient(140deg,#a51616,#5a0000)' }}>✦</div>
        <div className="flex-1 min-w-[220px]">
          <div className="text-[15px] font-semibold flex items-center gap-2">
            AI recommendations
            <span className="pill mono" style={{ background: 'rgba(139,92,246,0.16)', border: '1px solid rgba(139,92,246,0.3)', color: '#c4b5fd' }}>GEMINI</span>
          </div>
          <div className="text-[12px] text-white/55">Generated by Google Gemini from your live backlog, deadlines, and capacity.</div>
        </div>
        <div className="flex items-center gap-2">
          <span className="pill" style={{ background: geminiOn ? 'rgba(52,211,153,0.15)' : 'rgba(255,255,255,0.06)', border: '1px solid var(--line-strong)', color: geminiOn ? '#6ee7b7' : 'var(--ink-3)' }}>
            <span className="pill-dot" style={{ background: geminiOn ? '#34d399' : '#9a98b3' }} />
            {geminiOn ? 'Gemini connected' : 'Heuristic mode'}
          </span>
          <button className="btn btn-primary" onClick={handleGenerate} disabled={loading}>
            {loading ? <span className="blink">Generating…</span> : <><span>✦</span>Generate</>}
          </button>
        </div>
      </div>

      {/* Recommendations grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 md:gap-4 mt-4 md:mt-5">
        {recs.length === 0 && !loading && (
          <div className="md:col-span-2 text-center py-14 text-white/45">
            <div className="text-3xl mb-2">✦</div>
            <div className="text-[13.5px]">No recommendations yet.</div>
            <div className="text-[12px] mt-0.5">Click Generate to analyse your workload.</div>
          </div>
        )}
        {recs.map((rec, i) => (
          <div key={i} className="p-4 rounded-xl fade-in" style={{ background: TONE_BG[rec.tone] || 'rgba(255,255,255,0.06)', border: `1px solid ${TONE_BORDER[rec.tone] || 'rgba(255,255,255,0.10)'}` }}>
            <div className="flex items-start gap-3">
              <div className="text-xl shrink-0">{rec.icon}</div>
              <div className="flex-1 min-w-0">
                <div className="text-[13.5px] font-semibold">{rec.title}</div>
                <div className="text-[12.5px] text-white/75 mt-1 leading-snug">{rec.body}</div>
                {rec.actionLabel && rec.actionType !== 'none' && (
                  <button className="btn mt-3" onClick={() => handleAction(rec)}>{rec.actionLabel} →</button>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
